format_version: 4
raster_params:
  # raster image size [pixels]
  raster_size:
    - 128
    - 128
  # raster's spatial resolution [meters per pixel]: the size in the real world one pixel corresponds to.
  pixel_size:
    - 0.5
    - 0.5
  # From 0 to 1 per axis, [0.5,0.5] would show the ego centered in the image.
  ego_center:
    - 0.25
    - 0.5
  map_type: "py_semantic"

  # the keys are relative to the dataset environment variable
  satellite_map_key: "aerial_map/aerial_map.png"
  semantic_map_key: "semantic_map/semantic_map.pb"
  dataset_meta_key: "meta.json"

  # e.g. 0.0 include every obstacle, 0.5 show those obstacles with >0.5 probability of being
  # one of the classes we care about (cars, bikes, peds, etc.), >=1.0 filter all other agents.
  filter_agents_threshold: 0.5

  # whether to completely disable traffic light faces in the semantic rasterizer
  disable_traffic_light_faces: False
model_params:
  future_delta_time: 0.1
  future_num_frames: 50
  future_step_size: 1
  history_delta_time: 0.1
  history_num_frames: 10
  history_step_size: 1
  # not used.
  model_architecture: resnet50
train_data_loader:
  batch_size: 12
  key: scenes/train_full.zarr
  num_workers: 4
  shuffle: true
valid_data_loader:
  batch_size: 32
  key: scenes/validate.zarr
  num_workers: 4
  shuffle: false
train_params:
  checkpoint_every_n_steps: 5000
  max_num_steps: 10000
